import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import localFont from 'next/font/local';

const inter = Inter({ subsets: ["latin"] });

// Font files can be colocated inside of `app`
const myFont = localFont({
  src: './cambria-font.ttf',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={myFont.className + ' h-full'}>
      <body className="h-full bg-gradient-to-t from-lowerGradient to-upperGradient">
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
