import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import localFont from 'next/font/local';
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

// Font files can be colocated inside of `app`
const myFont = localFont({
  src: './cambria-font.ttf',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <html lang="en" className={`${myFont.className} min-h-screen`}>
        <body className="min-h-screen bg-gradient-to-t from-lowerGradient to-upperGradient flex flex-col">
          <Navbar/>
          <div className="flex-grow h-[calc(100vh-40px)]">
            {children}
          </div>
        </body>
      </html>
    </SessionProvider>
  );
}
