import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import localFont from 'next/font/local';
import { firebaseApp } from './lib/firebase-config'
import { AuthContextProvider } from './utils/AuthContext'

const inter = Inter({ subsets: ["latin"] });

// Font files can be colocated inside of `app`
const myFont = localFont({
  src: './cambria-font.ttf',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Words",
  description: "Generated by create next app",
};

const initFirebase = () => {
  return firebaseApp;
};
initFirebase();


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" className={`${myFont.className} min-h-screen`}>
        <body className="min-h-screen bg-gradient-to-t from-lowerGradient to-upperGradient flex flex-col">
          <AuthContextProvider>
            <Navbar/>
            <div className="flex flex-grow justify-center">
              {children}
            </div>
          </AuthContextProvider>
        </body>
      </html>
  );
}
